In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
import numpy as np

In [4]:
df["income_cat"]=pd.cut(df["median_income"], bins=[0, 1.5, 3.0, 4.5, 6.0, 7.5, np.inf], labels=[1,2,3,4,5,6])

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df["income_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [6]:
for sett in (strat_train_set, strat_test_set):
    sett.drop(labels="income_cat", inplace=True, axis=1)

In [7]:
df =strat_train_set.copy()

In [8]:
housing= strat_train_set.drop("median_house_value", axis=1)
housing_label=strat_train_set["median_house_value"].copy()

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
housing_num = housing.select_dtypes(include=[np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [10]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2123.5   ,  433.5   , 1166.    ,
        408.    ,    3.5409])

In [11]:
X = imputer.transform(housing_num)

In [12]:
housing=pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [13]:
housing["ocean_proximity"]=df["ocean_proximity"]

In [14]:
housing_op=housing[["ocean_proximity"]]

In [15]:
from sklearn.preprocessing import OneHotEncoder

In [16]:
cat_encoder=OneHotEncoder()

In [17]:
housing_cat=cat_encoder.fit_transform(housing_op)

In [18]:
housing_cat.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], shape=(16512, 5))

In [19]:
housing_cat=pd.DataFrame(housing_cat.toarray(), columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'], index=housing_op.index)

In [20]:
housing_cat

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
6895         1.0     0.0     0.0       0.0         0.0
2880         0.0     1.0     0.0       0.0         0.0
13769        0.0     1.0     0.0       0.0         0.0
18349        0.0     0.0     0.0       0.0         1.0
16188        0.0     1.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
10505        1.0     0.0     0.0       0.0         0.0
19526        0.0     1.0     0.0       0.0         0.0
9347         0.0     0.0     0.0       1.0         0.0
3650         1.0     0.0     0.0       0.0         0.0
15088        1.0     0.0     0.0       0.0         0.0

[16512 rows x 5 columns]

In [21]:
df=pd.concat([housing, housing_cat], axis=1)

In [22]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,<1H OCEAN,1.0,0.0,0.0,0.0,0.0
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,INLAND,0.0,1.0,0.0,0.0,0.0
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,INLAND,0.0,1.0,0.0,0.0,0.0
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,NEAR OCEAN,0.0,0.0,0.0,0.0,1.0
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,INLAND,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10505,-117.72,33.43,5.0,1889.0,359.0,616.0,246.0,3.8992,<1H OCEAN,1.0,0.0,0.0,0.0,0.0
19526,-120.97,37.65,16.0,3960.0,716.0,1776.0,724.0,3.9886,INLAND,0.0,1.0,0.0,0.0,0.0
9347,-122.58,37.98,52.0,1180.0,216.0,467.0,197.0,4.9615,NEAR BAY,0.0,0.0,0.0,1.0,0.0
3650,-118.44,34.21,37.0,1665.0,335.0,1011.0,343.0,4.8703,<1H OCEAN,1.0,0.0,0.0,0.0,0.0
15088,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834,<1H OCEAN,1.0,0.0,0.0,0.0,0.0

In [23]:
df=df.drop("ocean_proximity", axis=1)

In [24]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,1.0,0.0,0.0,0.0,0.0
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,0.0,1.0,0.0,0.0,0.0
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,0.0,1.0,0.0,0.0,0.0
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,0.0,0.0,0.0,0.0,1.0
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10505,-117.72,33.43,5.0,1889.0,359.0,616.0,246.0,3.8992,1.0,0.0,0.0,0.0,0.0
19526,-120.97,37.65,16.0,3960.0,716.0,1776.0,724.0,3.9886,0.0,1.0,0.0,0.0,0.0
9347,-122.58,37.98,52.0,1180.0,216.0,467.0,197.0,4.9615,0.0,0.0,0.0,1.0,0.0
3650,-118.44,34.21,37.0,1665.0,335.0,1011.0,343.0,4.8703,1.0,0.0,0.0,0.0,0.0
15088,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834,1.0,0.0,0.0,0.0,0.0

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
standard_scaler = StandardScaler()

In [27]:
df_scaled= standard_scaler.fit_transform(df)

In [28]:
df_scaled=pd.DataFrame(df_scaled, columns=df.columns, index=df.index)

In [29]:
df_scaled

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,<1H OCEAN,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
6895,0.730643,-0.746937,-0.049939,0.595554,0.391949,0.750555,0.529466,0.721492,1.127082,-0.684483,-0.011006,-0.355754,-0.383179
2880,0.300955,-0.120100,0.506250,-0.442703,-0.264178,-0.340605,-0.225218,-1.314705,-0.887247,1.460957,-0.011006,-0.355754,-0.383179
13769,1.270252,-0.732904,-1.003406,0.535762,0.102767,0.171518,0.072404,0.189342,-0.887247,1.460957,-0.011006,-0.355754,-0.383179
18349,-1.297886,0.838867,-0.367761,0.600653,1.475773,5.131254,1.201772,0.117726,-0.887247,-0.684483,-0.011006,-0.355754,2.609748
16188,-0.868198,1.086796,1.539173,-0.702731,-0.747768,-0.749232,-0.748713,-0.807287,-0.887247,1.460957,-0.011006,-0.355754,-0.383179
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10505,0.925502,-1.032289,-1.877418,-0.342585,-0.426994,-0.719790,-0.668993,0.013538,1.127082,-0.684483,-0.011006,-0.355754,-0.383179
19526,-0.698321,0.941781,-1.003406,0.617339,0.440551,0.315162,0.601214,0.060580,-0.887247,1.460957,-0.011006,-0.355754,-0.383179
9347,-1.502738,1.096151,1.856996,-0.671212,-0.774499,-0.852727,-0.799203,0.572524,-0.887247,-0.684483,-0.011006,2.810934,-0.383179
3650,0.565763,-0.667413,0.665162,-0.446411,-0.485317,-0.367371,-0.411232,0.524534,1.127082,-0.684483,-0.011006,-0.355754,-0.383179
15088,1.330208,-1.322318,-0.526672,0.789301,0.248573,0.472189,0.415200,0.847149,1.127082,-0.684483,-0.011006,-0.355754,-0.383179