In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
import numpy as np

In [4]:
df["income_cat"]=pd.cut(df["median_income"], bins=[0, 1.5, 3.0, 4.5, 6.0, 7.5, np.inf], labels=[1,2,3,4,5,6])

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df["income_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [6]:
for sett in (strat_train_set, strat_test_set):
    sett.drop(labels="income_cat", inplace=True, axis=1)

In [7]:
df =strat_train_set.copy()

In [8]:
housing= strat_train_set.drop("median_house_value", axis=1)
housing_label=strat_train_set["median_house_value"].copy()

In [9]:
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446,<1H OCEAN
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750,INLAND
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333,INLAND
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972,NEAR OCEAN
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393,INLAND
...,...,...,...,...,...,...,...,...,...
10505,-117.72,33.43,5.0,1889.0,359.0,616.0,246.0,3.8992,<1H OCEAN
19526,-120.97,37.65,16.0,3960.0,716.0,1776.0,724.0,3.9886,INLAND
9347,-122.58,37.98,52.0,1180.0,216.0,467.0,197.0,4.9615,NEAR BAY
3650,-118.44,34.21,37.0,1665.0,335.0,1011.0,343.0,4.8703,<1H OCEAN
15088,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834,<1H OCEAN

In [10]:
housing_label

6895     258000.0
2880      57500.0
13769    220300.0
18349    387500.0
16188     77600.0
           ...
10505    500001.0
19526    137500.0
9347     292200.0
3650     185100.0
15088    232000.0
Name: median_house_value, Length: 16512, dtype: float64

In [11]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
housing_num = housing.select_dtypes(include=[np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [12]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2123.5   ,  433.5   , 1166.    ,
        408.    ,    3.5409])

In [13]:
X = imputer.transform(housing_num)

In [14]:
X

array([[-1.1811e+02,  3.4040e+01,  2.8000e+01, ...,  2.2640e+03,
         6.9700e+02,  5.2446e+00],
       [-1.1897e+02,  3.5380e+01,  3.5000e+01, ...,  1.0410e+03,
         4.1300e+02,  1.3750e+00],
       [-1.1703e+02,  3.4070e+01,  1.6000e+01, ...,  1.6150e+03,
         5.2500e+02,  4.2333e+00],
       ...,
       [-1.2258e+02,  3.7980e+01,  5.2000e+01, ...,  4.6700e+02,
         1.9700e+02,  4.9615e+00],
       [-1.1844e+02,  3.4210e+01,  3.7000e+01, ...,  1.0110e+03,
         3.4300e+02,  4.8703e+00],
       [-1.1691e+02,  3.2810e+01,  2.2000e+01, ...,  1.9520e+03,
         6.5400e+02,  5.4834e+00]], shape=(16512, 8))

In [15]:
housing_tr=pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [16]:
housing_tr

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
6895,-118.11,34.04,28.0,3913.0,696.0,2264.0,697.0,5.2446
2880,-118.97,35.38,35.0,1673.0,426.0,1041.0,413.0,1.3750
13769,-117.03,34.07,16.0,3784.0,577.0,1615.0,525.0,4.2333
18349,-122.17,37.43,24.0,3924.0,1142.0,7174.0,950.0,4.0972
16188,-121.31,37.96,48.0,1112.0,227.0,583.0,216.0,2.3393
...,...,...,...,...,...,...,...,...
10505,-117.72,33.43,5.0,1889.0,359.0,616.0,246.0,3.8992
19526,-120.97,37.65,16.0,3960.0,716.0,1776.0,724.0,3.9886
9347,-122.58,37.98,52.0,1180.0,216.0,467.0,197.0,4.9615
3650,-118.44,34.21,37.0,1665.0,335.0,1011.0,343.0,4.8703
15088,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834

In [18]:
housing_tr.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16512 entries, 6895 to 15088
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           16512 non-null  float64
 1   latitude            16512 non-null  float64
 2   housing_median_age  16512 non-null  float64
 3   total_rooms         16512 non-null  float64
 4   total_bedrooms      16512 non-null  float64
 5   population          16512 non-null  float64
 6   households          16512 non-null  float64
 7   median_income       16512 non-null  float64
dtypes: float64(8)
memory usage: 1.1 MB