In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
import numpy as np

In [4]:
df["income_cat"]=pd.cut(df["median_income"], bins=[0, 1.5, 3.0, 4.5, 6.0, 7.5, np.inf], labels=[1,2,3,4,5,6])

In [5]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(df, df["income_cat"]):
    strat_train_set = df.loc[train_index]
    strat_test_set = df.loc[test_index]

In [6]:
for sett in (strat_train_set, strat_test_set):
    sett.drop(labels="income_cat", inplace=True, axis=1)

In [7]:
df =strat_train_set.copy()

In [8]:
housing= strat_train_set.drop("median_house_value", axis=1)
housing_label=strat_train_set["median_house_value"].copy()

In [9]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")
housing_num = housing.select_dtypes(include=[np.number])
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [10]:
imputer.statistics_

array([-118.51  ,   34.26  ,   29.    , 2123.5   ,  433.5   , 1166.    ,
        408.    ,    3.5409])

In [11]:
X = imputer.transform(housing_num)

In [12]:
housing=pd.DataFrame(X, columns=housing_num.columns, index=housing_num.index)

In [13]:
housing["ocean_proximity"]=df["ocean_proximity"]

In [14]:
housing=housing[["ocean_proximity"]]

In [15]:
housing

      ocean_proximity
6895        <1H OCEAN
2880           INLAND
13769          INLAND
18349      NEAR OCEAN
16188          INLAND
...               ...
10505       <1H OCEAN
19526          INLAND
9347         NEAR BAY
3650        <1H OCEAN
15088       <1H OCEAN

[16512 rows x 1 columns]

In [16]:
from sklearn.preprocessing import OneHotEncoder

In [17]:
cat_encoder=OneHotEncoder()

In [28]:
housing_cat=cat_encoder.fit_transform(housing)

In [29]:
housing_cat.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       ...,
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], shape=(16512, 5))

In [30]:
housing_cat=pd.DataFrame(housing_cat.toarray(), columns=['<1H OCEAN', 'INLAND', 'ISLAND', 'NEAR BAY', 'NEAR OCEAN'], index=housing.index)

In [31]:
housing_cat

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
6895         1.0     0.0     0.0       0.0         0.0
2880         0.0     1.0     0.0       0.0         0.0
13769        0.0     1.0     0.0       0.0         0.0
18349        0.0     0.0     0.0       0.0         1.0
16188        0.0     1.0     0.0       0.0         0.0
...          ...     ...     ...       ...         ...
10505        1.0     0.0     0.0       0.0         0.0
19526        0.0     1.0     0.0       0.0         0.0
9347         0.0     0.0     0.0       1.0         0.0
3650         1.0     0.0     0.0       0.0         0.0
15088        1.0     0.0     0.0       0.0         0.0

[16512 rows x 5 columns]